#!/bin/bash

unset map
declare -A map

idx=1
while read -r line; do

  map[$idx]="$line"
  echo "$idx $(basename "$line")"
  idx=$((idx + 1))

done < <(find ~ -type f -name "docker-compose*" -print0 | xargs -0 dirname)

if [[ "${#map[@]}" -eq 0 ]]; then
  echo "No such directory found"
  return
fi

echo -n "Choose line index: "
read -r num

cd "${map[$num]}" || echo "Change of directory failed"

echo "Executing docker-compose of $(basename "${map[$num]}")"
echo

docker-compose up -d
docker ps -a
